project:
  type: website
  output-dir: docs

website:
  title: "First Break AI"
  site-url: "https://thefirehacker.github.io/firstbreakai/"
  google-analytics: "G-V1B8R98P79"
  repo-url: "https://github.com/thefirehacker/firstbreakai"
  repo-actions: [edit, source]
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: checklist.qmd
        text: Checklist
      - href: setup.qmd
        text: AI Setup
      - href: roadmap.qmd
        text: Roadmap
    right:
      - icon: discord
        href: "https://discord.gg/QZuBvfcj"
        text: Discord
      - icon: github
        href: "https://github.com/thefirehacker/firstbreakai"
        text: Repo
